---
dependency:
  name: galaxy
#  options:
#    role-file: ./molecule/resources/playbooks/requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu18
    image: solita/ubuntu-systemd:18.04
    groups:
      - minecraftserver
    command: /sbin/init
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
  - name: centos8
    image: centos:8
    groups:
      - minecraftserver
    command: /usr/sbin/init
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
  inventory:
    group_vars:
      minecraftserver:
        user_accept_minecraft_eula: ${mc_accept_eula:-false}
        minecraft_server: spigot
        mc_version: 1.13.1
        minecraft_plugins_set_version: "minimal"
        minecraft_plugin_sets:
          minimal:
            vault:
              src: https://media.forgecdn.net/files/2615/750/Vault.jar
            LuckPerms:
              src: https://ci.lucko.me/job/LuckPerms/lastSuccessfulBuild/
              type: "jenkins_latest"
              jenkins_artefact_path: "/artifact/bukkit/build/libs"
              dest: LuckPerms.jar
              force: true
              config:
                - src_dir: "{{ playbook_dir }}/templates/LuckPerms/yaml-storage/groups"
                  dest: LuckPerms/yaml-storage/groups/
                  force: true
            permissionsEx:
              src: https://media.forgecdn.net/files/909/154/PermissionsEx-1.23.4.jar
              dest: PermissionsEx.jar
              config:
                - src: config_permissionex.yml.j2
                  dest: PermissionsEx/config.yml
            tne:
              src: https://github.com/TheNewEconomy/TNE-Bukkit/releases/download/Beta-1.1.3/Beta.1.1.3.zip
              type: "archive"
  playbooks:
    converge: ../resources/playbooks/playbook.yml
  lint:
    name: ansible-lint
    enabled: false
    options:
      x:
        - ANSIBLE0006
        - ANSIBLE0010
        - ANSIBLE0011
        - ANSIBLE0016
scenario:
  name: spigot_with_plugins
verifier:
  name: testinfra
  directory: ../resources/tests/
  additional_files_or_dirs:
    - ../tests_plugins/
  lint:
    name: flake8
