---

- name: install spigot package
  package:
    name: "{{ item }}"
  register: pack_res
  retries: 5
  until: pack_res is success
  with_items: "{{ dependencies_spigot }}"
  when: minecraft_server == 'spigot'

- name: create Minecraft group
  group:
    state: present
    name: "{{ minecraft_group }}"
    system: true

- name: create Minecraft user
  user:
    state: present
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    system: true

- name: set executable name (Minecraft)
  set_fact:
    minecraft_jar: minecraft_server.jar
  when: minecraft_server == 'minecraft'

- name: set executable name (Spigot)
  set_fact:
    minecraft_jar: spigot.jar
  when: minecraft_server == 'spigot'
