---
dependency:
  name: galaxy
driver:
  name: docker
#lint:
#  name: yamllint
#  enabled: false
platforms:
  - name: debian
    image: jrei/systemd-debian:10
    command: /sbin/init
    groups:
      - minecraftserver
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
  - name: ubuntu16
    image: solita/ubuntu-systemd:16.04
    groups:
      - minecraftserver
    command: /sbin/init
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
  - name: ubuntu18
    image: solita/ubuntu-systemd:18.04
    groups:
      - minecraftserver
    command: /sbin/init
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
      - /run/lock
  - name: fedora
    image: fedora:29
    groups:
      - minecraftserver
    command: /usr/sbin/init
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
  - name: centos7
    image: centos:latest
    groups:
      - minecraftserver
    command: /usr/sbin/init
    security_opts:
      - seccomp=unconfined
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
  inventory:
    group_vars:
      minecraftserver:
        user_accept_minecraft_eula: ${mc_accept_eula}
        minecraft_server: spigot
        mc_version: 1.13.1
  playbooks:
    converge: ../resources/playbooks/playbook.yml
  lint:
    name: ansible-lint
    enabled: false
    options:
      x:
        - ANSIBLE0006
        - ANSIBLE0010
        - ANSIBLE0011
        - ANSIBLE0016
scenario:
  name: spigot
verifier:
  name: testinfra
  directory: ../resources/tests/
  additional_files_or_dirs:
    - ../tests_spigot/
  lint:
    name: flake8
